apiVersion: apps/v1
kind: Deployment
metadata:
  name: stellar-federation
spec:
  selector:
    matchLabels:
      app: stellar-federation
  template:
    metadata:
      labels:
        app: stellar-federation
    spec:
      containers:
      - name: stellar-federation
        image: docker.io/<username>/stellar-federation-server:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: stellar-federation
spec:
  selector:
    app: stellar-federation
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stellar-federation
  labels:
    name: stellar-federation
spec:
  rules:
  - host: federation.<your-domain>.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: stellar-federation
            port: 
              number: 80

